server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db/changelog/000-main.xml

springdoc:
  swagger-ui:
    url: /v3/api-docs.yaml
    path: /swagger-ui
    enabled: true
    disable-swagger-default-url: true

  api-docs:
    enabled: true
